name: build the microservice workflow 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    id: build the python lambda function 
    steps:
      - name: checkout code 
        uses: actions/checkout@v2.3.4
      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: install libraries
        run:  |
          cd function 
          if [-f requirements.txt]; then pip install -r requirements.txt -t .; fi
      - name: zip the function up
        run: |
          cd function 
          zip -r ../${{ github.sha }}.zip .
      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{github.sha}}.zip